version: "3"

name: autoapply

services:
  postgres:
    container_name: autoapply-postgres
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: autoapply
    ports:
      - "5436:5432"

  api:
    build: ./
    container_name: autoapply-api
    environment:
      NODE_DEBUG: info
      NODE_ENV: dev
      DB_CONNECTION: "postgresql://admin:password@postgres/autoapply"
    volumes:
      - ./:/app
    ports:
      - 4000:4000
    depends_on:
      - postgres
volumes:
  postgres-data:
