version: "3"

name: autoapply

services:
  cockroachdb:
    container_name: autoapply-cockroachdb
    image: cockroachdb/cockroach:latest-v23.1
    command: start-single-node --insecure
    ports:
      - "26257:26257" # Default CockroachDB port for SQL
      - "8080:8080" # Default CockroachDB port for the web UI
    volumes:
      - cockroachdb-data:/cockroach/cockroach-data

  api:
    build: ./
    container_name: autoapply-api
    environment:
      NODE_DEBUG: info
      NODE_ENV: local
      DB_CONNECTION: "postgresql://system@cockroachdb:26257/autoapply?sslmode=disable"
    ports:
      - 4000:4000
    depends_on:
      - cockroachdb
volumes:
  cockroachdb-data:
