import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "../styles/app.module.css";

import "@mantine/core/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { DoubleNavbar } from "@/componenets/DoubleNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <MantineProvider>
          <div className={styles.pageWrapper}>
            <DoubleNavbar />
            <main className={styles.main}>{children}</main>
          </div>
        </MantineProvider>
      </body>
    </html>
  );
}
